Set NODE_PATH

diff --git a/tools/make/lib/lint/markdown/Makefile b/tools/make/lib/lint/markdown/Makefile
--- a/tools/make/lib/lint/markdown/Makefile
+++ b/tools/make/lib/lint/markdown/Makefile
@@ -42,13 +42,13 @@ ifeq ($(FAIL_FAST), true)
 	$(QUIET) $(FIND_MARKDOWN_CMD) | grep '^[\/]\|^[a-zA-Z]:[/\]' | while read -r file; do \
 		echo ''; \
 		echo "Linting file: $$file"; \
-		$(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || exit 1; \
+		NODE_PATH="$(NODE_PATH)" $(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || exit 1; \
 	done
 else
 	$(QUIET) $(FIND_MARKDOWN_CMD) | grep '^[\/]\|^[a-zA-Z]:[/\]' | while read -r file; do \
 		echo ''; \
 		echo "Linting file: $$file"; \
-		$(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || echo 'Linting failed.'; \
+		NODE_PATH="$(NODE_PATH)" $(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || echo 'Linting failed.'; \
 	done
 endif
 
@@ -72,13 +72,13 @@ ifeq ($(FAIL_FAST), true)
 	$(QUIET) for file in $(FILES); do \
 		echo ''; \
 		echo "Linting file: $$file"; \
-		$(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || exit 1; \
+		NODE_PATH="$(NODE_PATH)" $(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || exit 1; \
 	done
 else
 	$(QUIET) for file in $(FILES); do \
 		echo ''; \
 		echo "Linting file: $$file"; \
-		$(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || echo 'Linting failed.'; \
+		NODE_PATH="$(NODE_PATH)" $(MARKDOWN_LINT) $(MARKDOWN_LINT_FLAGS) $$file || echo 'Linting failed.'; \
 	done
 endif
 
