Update Python version

diff --git a/tools/scripts/check_python b/tools/scripts/check_python
--- a/tools/scripts/check_python
+++ b/tools/scripts/check_python
@@ -42,7 +42,7 @@ if [[ -x "${PYTHON}" ]] && "${PYTHON}" --version >/dev/null; then
 	echo 'Python is installed.' >&2
 	exit 0
 else
-	echo 'ERROR: missing dependency. Please download Python version 2.7 (https://www.python.org/). Once installed, run the command again.' >&2
+	echo 'ERROR: missing dependency. Please download Python version >=2.7 (https://www.python.org/). Once installed, run the command again.' >&2
 	exit 1
 fi
 
