Update links

diff --git a/tools/scripts/check_curl b/tools/scripts/check_curl
--- a/tools/scripts/check_curl
+++ b/tools/scripts/check_curl
@@ -42,7 +42,7 @@ if [[ -x "${CURL}" ]] && "${CURL}" --version >/dev/null; then
 	echo 'curl is installed.' >&2
 	exit 0
 else
-	echo 'ERROR: missing dependency. Please install curl (http://curl.haxx.se/). Once installed, run the command again.' >&2
+	echo 'ERROR: missing dependency. Please install curl (https://curl.se/). Once installed, run the command again.' >&2
 	exit 1
 fi
 
diff --git a/tools/scripts/check_wget b/tools/scripts/check_wget
--- a/tools/scripts/check_wget
+++ b/tools/scripts/check_wget
@@ -42,7 +42,7 @@ if [[ -x "${WGET}" ]] && "${WGET}" --version >/dev/null; then
 	echo 'wget is installed.' >&2
 	exit 0
 else
-	echo 'ERROR: missing dependency. Please install wget (http://www.gnu.org/software/wget). Once installed, run the command again.' >&2
+	echo 'ERROR: missing dependency. Please install wget (https://www.gnu.org/software/wget/). Once installed, run the command again.' >&2
 	exit 1
 fi
 
