Add version info

diff --git a/tools/scripts/check_cmake b/tools/scripts/check_cmake
--- a/tools/scripts/check_cmake
+++ b/tools/scripts/check_cmake
@@ -26,7 +26,7 @@ if [[ -x "${CMAKE}" ]] && "${CMAKE}" --version >/dev/null; then
 	echo 'CMake is installed.' >&2
 	exit 0
 else
-	echo 'ERROR: missing dependency. Please download CMake (https://cmake.org/). Once installed, run the command again.' >&2
+	echo 'ERROR: missing dependency. Please download CMake version >= 3.4.3 (https://cmake.org/). Once installed, run the command again.' >&2
 	exit 1
 fi
 
diff --git a/tools/scripts/check_gfortran b/tools/scripts/check_gfortran
--- a/tools/scripts/check_gfortran
+++ b/tools/scripts/check_gfortran
@@ -26,7 +26,7 @@ if [[ -x "${GFORTRAN}" ]] && "${GFORTRAN}" --version >/dev/null; then
 	echo 'gfortran is installed.' >&2
 	exit 0
 else
-	echo 'ERROR: missing dependency. Please download gfortran (https://gcc.gnu.org/fortran/). Once installed, run the command again.' >&2
+	echo 'ERROR: missing dependency. Please download gfortran version >= 4.8 (https://gcc.gnu.org/fortran/). Once installed, run the command again.' >&2
 	exit 1
 fi
 
diff --git a/tools/scripts/check_pandoc b/tools/scripts/check_pandoc
--- a/tools/scripts/check_pandoc
+++ b/tools/scripts/check_pandoc
@@ -26,7 +26,7 @@ if [[ -x "${PANDOC}" ]] && "${PANDOC}" -v >/dev/null; then
 	echo 'pandoc is installed.' >&2
 	exit 0
 else
-	echo 'ERROR: missing dependency. Please download pandoc (http://pandoc.org/). Once installed, run the command again.' >&2
+	echo 'ERROR: missing dependency. Please download pandoc version >= 1.18 (http://pandoc.org/). Once installed, run the command again.' >&2
 	exit 1
 fi
 
