Update error message

diff --git a/tools/scripts/npm_publish b/tools/scripts/npm_publish
--- a/tools/scripts/npm_publish
+++ b/tools/scripts/npm_publish
@@ -270,7 +270,7 @@ publish_bundles() {
 	make clean-dist-bundles
 	if [[ "$?" -ne 0 ]]; then
 		echo '' >&2
-		echo 'Error: unexpected error. Encountered an error when attempting to remove bundles artifacts.' >&2
+		echo 'Error: unexpected error. Encountered an error when attempting to remove bundle artifacts.' >&2
 		echo '' >&2
 		return 1
 	fi
