Add support for linting shell script files pre-commit

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -203,6 +203,23 @@ run_lint() {
 		fi
 	fi
 
+	# Lint shell script files...
+	files=$(echo "${changed_files}" | while read -r file; do head -n1 "$file" | grep -q '^\#\!/usr/bin/env bash' && echo "$file"; done | tr '\n' ' ')
+	if [[ -n "${files}" ]]; then
+		make check-shell-linters > /dev/null >&2
+		if [[ "$?" -ne 0 ]]; then
+			echo '' >&2
+			echo 'Unable to lint shell script files. Ensure that linters are installed.' >&2
+		else
+			make FILES="${files}" lint-shell-files > /dev/null >&2
+			if [[ "$?" -ne 0 ]]; then
+				echo '' >&2
+				echo 'Shell script lint errors.' >&2
+				return 1
+			fi
+		fi
+	fi
+
 	# Lint license headers...
 	files=$(echo "${changed_files}" | tr '\n' ' ')
 	if [[ -n "${files}" ]]; then
