Add support for linting Python

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -79,7 +79,7 @@ run_lint() {
 	# Lint Markdown files...
 	files=$(echo "${changed_files}" | grep '\.md$' | tr '\n' ' ')
 	if [[ -n "${files}" ]]; then
-		make MARKDOWN_FILES="${files}" lint-markdown > /dev/null
+		make MARKDOWN_FILES="${files}" lint-markdown > /dev/null >&2
 		if [[ "$?" -ne 0 ]]; then
 			echo '' >&2
 			echo 'Markdown lint errors.' >&2
@@ -139,6 +139,23 @@ run_lint() {
 			echo '' >&2
 			echo 'JavaScript lint errors for benchmark files.' >&2
 			return 1
+		fi
+	fi
+
+	# Lint Python files...
+	files=$(echo "${changed_files}" | grep '\.py$' | tr '\n' ' ')
+	if [[ -n "${files}" ]]; then
+		make check-python-linters > /dev/null >&2
+		if [[ "$?" -ne 0 ]]; then
+			echo '' >&2
+			echo 'Unable to lint Python files. Ensure that linters are installed.' >&2
+		else
+			make PYTHON_FILES="${files}" lint-python-files > /dev/null >&2
+			if [[ "$?" -ne 0 ]]; then
+				echo '' >&2
+				echo 'Python lint errors.' >&2
+				return 1
+			fi
 		fi
 	fi
 
