Add support for linting REPL help files pre-commit

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -34,6 +34,9 @@ lint_filenames="${root}/lib/node_modules/@stdlib/_tools/lint/filenames/bin/cli"
 # Define the path to a utility for linting package.json files:
 lint_package_json="${root}/lib/node_modules/@stdlib/_tools/lint/pkg-json/bin/cli"
 
+# Define the path to a utility for linting REPL help files:
+lint_repl_help="${root}/lib/node_modules/@stdlib/_tools/lint/repl-help/bin/cli"
+
 # Define the path to ESLint configuration file for linting examples:
 eslint_examples_conf="${root}/etc/eslint/.eslintrc.examples.js"
 
@@ -116,6 +119,17 @@ run_lint() {
 		if [[ "$?" -ne 0 ]]; then
 			echo '' >&2
 			echo 'Package.json lint errors.' >&2
+			return 1
+		fi
+	fi
+
+	# Lint REPL help files...
+	files=$(echo "${changed_files}" | grep 'repl\.txt$' )
+	if [[ -n "${files}" ]]; then
+		echo "${files}" | "${lint_repl_help}" >&2
+		if [[ "$?" -ne 0 ]]; then
+			echo '' >&2
+			echo 'REPL help lint errors.' >&2
 			return 1
 		fi
 	fi
