Run C examples as part of pre-push hook

diff --git a/tools/git/hooks/pre-push b/tools/git/hooks/pre-push
--- a/tools/git/hooks/pre-push
+++ b/tools/git/hooks/pre-push
@@ -117,7 +117,19 @@ main() {
 		make FILES="${files}" examples-files > /dev/null >&2
 		if [[ "$?" -ne 0 ]]; then
 			echo '' >&2
-			echo 'Encountered an error when running examples.' >&2
+			echo 'Encountered an error when running JavaScript examples.' >&2
+			on_error 1
+		fi
+	fi
+
+	# Run C example files...
+	files=$(echo "${changed_files}" | grep '/examples/.*\.c$' | grep -v '/examples/fixtures/.*\.c$' | tr '\n' ' ')
+	if [[ -n "${files}" ]]; then
+		echo 'Running C example files...' >&2
+		make FILES="${files}" examples-c-files > /dev/null >&2
+		if [[ "$?" -ne 0 ]]; then
+			echo '' >&2
+			echo 'Encountered an error when running C examples.' >&2
 			on_error 1
 		fi
 	fi
