Add support for linting TypeScript declaration files pre-commit

diff --git a/tools/git/hooks/pre-commit b/tools/git/hooks/pre-commit
--- a/tools/git/hooks/pre-commit
+++ b/tools/git/hooks/pre-commit
@@ -234,6 +234,17 @@ run_lint() {
 		fi
 	fi
 
+	# Lint TypeScript declaration files...
+	files=$(echo "${changed_files}" | grep '\.d\.ts$' | tr '\n' ' ')
+	if [[ -n "${files}" ]]; then
+		make TYPESCRIPT_DECLARATIONS_LINTER=dtslint FILES="${files}" lint-typescript-declaration-files > /dev/null >&2
+		if [[ "$?" -ne 0 ]]; then
+			echo '' >&2
+			echo 'TypeScript declaration file lint errors.' >&2
+			return 1
+		fi
+	fi
+
 	# Lint license headers...
 	files=$(echo "${changed_files}" | tr '\n' ' ')
 	if [[ -n "${files}" ]]; then
