Update style

diff --git a/tools/git/hooks/pre-push b/tools/git/hooks/pre-push
--- a/tools/git/hooks/pre-push
+++ b/tools/git/hooks/pre-push
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 #
-# A git hook called by "git push" after it has checked the remote status, but before anything has been pushed.
-#
-# If this script exits with a non-zero status, nothing will be pushed.
+# A git hook called by `git push` after it has checked the remote status, but before anything has been pushed. If this script exits with a non-zero status, nothing will be pushed.
 #
 # This hook is called with the following parameters:
 #
-# $1 - name of the remote to which the push is being done
-# $2 - URL to which the push is being done
+# * `$1` - name of the remote to which the push is being done
+# * `$2` - URL to which the push is being done
 #
 # If pushing without using a named remote, these arguments will be equal.
 #
-# Information about the commits which are being pushed is supplied as lines to stdin in the form:
+# Information about the commits which are being pushed is supplied as lines to `stdin` in the form:
 #
+# ``` text
 # <local ref> <local sha1> <remote ref> <remote sha1>
-#
+# ```
+
 
 # VARIABLES #
 
@@ -25,7 +25,7 @@ url="$2"
 export GIT_HOOK_TEST='make test'
 
 # Determine the current branch:
-export GIT_CURRENT_BRANCH=`git name-rev --name-only HEAD`
+export GIT_CURRENT_BRANCH="$(git name-rev --name-only HEAD)"
 
 
 # FUNCTIONS #
@@ -45,8 +45,8 @@ cleanup() {
 
 # Checks if commits exist to push, as `git push` will execute regardless of whether commits exist to push or not.
 has_commits() {
-	echo 'Checking for commits to push...'
-	local commits=`git log origin/$GIT_CURRENT_BRANCH..$GIT_CURRENT_BRANCH --oneline`
+	echo 'Checking for commits to push...' >&2
+	local commits="$(git log origin/${GIT_CURRENT_BRANCH}..${GIT_CURRENT_BRANCH} --oneline)"
 	if [[ -z "$commits" ]]; then
 	    return 1
 	fi
@@ -55,10 +55,10 @@ has_commits() {
 
 # Runs tests.
 run_tests() {
-	echo 'Running tests...'
-	$GIT_HOOK_TEST
+	echo 'Running tests...' >&2
+	"$(${GIT_HOOK_TEST})"
 	if [[ "$?" -ne 0 ]]; then
-        echo "$GIT_HOOK_TEST failed." >&2
+        echo "${GIT_HOOK_TEST} failed." >&2
         return 1
     fi
     echo 'Tests passed.' >&2
