Return to original directory

diff --git a/.github/workflows/scripts/test_install b/.github/workflows/scripts/test_install
--- a/.github/workflows/scripts/test_install
+++ b/.github/workflows/scripts/test_install
@@ -55,6 +55,9 @@ heartbeat_interval='30s'
 # Declare a variable for storing the heartbeat process id:
 heartbeat_pid=""
 
+# Get the current working directory:
+working_dir=$(pwd)
+
 
 # FUNCTIONS #
 
@@ -125,8 +128,41 @@ install_init() {
 install_test() {
 	echo 'Testing installation...' >&2
 
-	echo 'Creating test script...' >&2
+	echo 'Creating test script (require global namespace)...' >&2
 	echo 'var stdlib = require( "@stdlib/stdlib" ); console.log( stdlib.math.base.special.sin( 3.14 ) );' > "${install_dir}/script.js"
+
+	echo 'Running test script...' >&2
+	node "${install_dir}/script.js"
+	if [[ "$?" -ne 0 ]]; then
+		echo "Encountered an error when running test script." >&2
+		return 1
+	fi
+	echo 'Successfully ran test script.' >&2
+
+	echo 'Creating test script (import global namespace)...' >&2
+	echo 'import stdlib from "@stdlib/stdlib"; console.log( stdlib.math.base.special.sin( 3.14 ) );' > "${install_dir}/script.js"
+
+	echo 'Running test script...' >&2
+	node "${install_dir}/script.js"
+	if [[ "$?" -ne 0 ]]; then
+		echo "Encountered an error when running test script." >&2
+		return 1
+	fi
+	echo 'Successfully ran test script.' >&2
+
+	echo 'Creating test script (require individual package)...' >&2
+	echo 'var sin = require( "@stdlib/math/base/special/sin" ); console.log( sin( 3.14 ) );' > "${install_dir}/script.js"
+
+	echo 'Running test script...' >&2
+	node "${install_dir}/script.js"
+	if [[ "$?" -ne 0 ]]; then
+		echo "Encountered an error when running test script." >&2
+		return 1
+	fi
+	echo 'Successfully ran test script.' >&2
+
+	echo 'Creating test script (import individual package)...' >&2
+	echo 'import sin from "@stdlib/math/base/special/sin"; console.log( sin( 3.14 ) );' > "${install_dir}/script.js"
 
 	echo 'Running test script...' >&2
 	node "${install_dir}/script.js"
@@ -140,8 +176,12 @@ install_test() {
 
 # Performs local installation cleanup tasks.
 install_clean() {
+	echo 'Returning to original directory...' >&2
+	cwd "${working_dir}" || return 1
+
 	echo 'Removing installation directory...' >&2
 	rm -rf "${install_dir}" || return 1
+
 	return 0
 }
 
