Disable linting Markdown files
Linting Markdown files consumes too much time causing builds to
time out. We either need a strategy for parallelization or lint
only those files which have changed.

diff --git a/tools/ci/circle/script b/tools/ci/circle/script
--- a/tools/ci/circle/script
+++ b/tools/ci/circle/script
@@ -297,12 +297,13 @@ lint() {
 		echo 'Linting package.json failed.' >&2
 		return 1
 	fi
-	echo 'Linting Markdown files...' >&2
-	make lint-markdown >> "$1" 2>&1
-	if [[ "$?" -ne 0 ]]; then
-		echo 'Linting Markdown failed.' >&2
-		return 1
-	fi
+	# FIXME: linting of Markdown files takes too long; need to speed-up via distributed tasks or only linting files which changed
+	# echo 'Linting Markdown files...' >&2
+	# make lint-markdown >> "$1" 2>&1
+	# if [[ "$?" -ne 0 ]]; then
+	# 	echo 'Linting Markdown failed.' >&2
+	# 	return 1
+	# fi
 	echo 'Linting passed.' >&2
 	return 0
 }
