Add linting package.json files to lint task

diff --git a/tools/ci/circle/script b/tools/ci/circle/script
--- a/tools/ci/circle/script
+++ b/tools/ci/circle/script
@@ -228,6 +228,12 @@ lint() {
 		echo 'Linting failed.' >&2
 		return 1
 	fi
+	echo 'Linting package.json files...' >&2
+	make lint-pkg-json >> "$1" 2>&1
+	if [[ "$?" -ne 0 ]]; then
+		echo 'Linting failed.' >&2
+		return 1
+	fi
 	echo 'Linting passed.' >&2
 	return 0
 }
