Lint header filenames on build

diff --git a/tools/ci/circle/script b/tools/ci/circle/script
--- a/tools/ci/circle/script
+++ b/tools/ci/circle/script
@@ -283,6 +283,11 @@ lint() {
 		echo 'Linting filenames failed.' >&2
 		return 1
 	fi
+	make lint-header-filenames >> "$1" 2>&1
+	if [[ "$?" -ne 0 ]]; then
+		echo 'Linting filenames failed.' >&2
+		return 1
+	fi
 	echo 'Linting package.json files...' >&2
 	make lint-pkg-json >> "$1" 2>&1
 	if [[ "$?" -ne 0 ]]; then
