Allocate tasks based on VM index and run canary tests

diff --git a/tools/ci/circle b/tools/ci/circle
--- a/tools/ci/circle
+++ b/tools/ci/circle
@@ -8,10 +8,14 @@
 # DEPENDENCIES #
 
 # Source nvm to ensure that the `nvm` command is available:
-. /opt/circleci/.nvm/nvm.sh
+# . /opt/circleci/.nvm/nvm.sh
 
 
 # VARIABLES #
+
+# Determine the root project directory:
+root_dir=$(dirname "$0")/../..
+root_dir=$(cd "${root_dir}" && echo $PWD)
 
 # Define a username:
 username="${CIRCLE_USERNAME}"
@@ -24,6 +28,27 @@ index="${CIRCLE_NODE_INDEX}"
 
 # Define an output file to store log output:
 log_file='/var/log/circle-ci.log'
+
+# Define an output file to store unit test results:
+tests_log_file="${CIRCLE_TEST_REPORTS}/junit/test-results.xml"
+
+# Define the pattern for test filenames:
+tests_pattern='test*.js'
+
+# Define the pattern for filtering tests based on their file path:
+tests_filter='.*/.*'
+
+# Define the directory path of top-level node module dependencies:
+node_modules="${root_dir}/node_modules"
+
+# Define the directory path for build artifacts:
+build_dir="${root_dir}/build"
+
+# Define the directory path for reports:
+reports_dir="${root_dir}/reports"
+
+# Define the directory for top-level tools:
+tools_dir="${root_dir}/tools"
 
 # Define a heartbeat interval to periodically print messages in order to prevent Circle CI from prematurely ending a build due to long running commands:
 heartbeat_interval='30s'
@@ -196,12 +221,70 @@ lint() {
 	return 0
 }
 
+# Finds test files.
+find_tests() {
+	local kernel
+	local tests
+
+	kernel=$(uname -s)
+
+	# On Mac OSX, in order to use `|` and other regular expression operators, we need to use enhanced regular expression syntax (-E); see https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man7/re_format.7.html#//apple_ref/doc/man/7/re_format.
+	if [[ "${kernel}" = "Darwin" ]]; then
+		tests=$(find -E "${root_dir}" -name "${tests_pattern}" -regex "${tests_filter}" -not -path "${root_dir}/.*" -not -path "${node_modules}/*" -not -path "${tools_dir}/*" -not -path "${build_dir}/*" -not -path "${reports_dir}/*")
+	else
+		tests=$(find "${root_dir}" -regextype posix-extended -name "${tests_pattern}" -regex "${tests_filter}" -not -path "${root_dir}/.*" -not -path "${node_modules}/*" -not -path "${tools_dir}/*" -not -path "${build_dir}/*" -not -path "${reports_dir}/*")
+	fi
+	echo "${tests}"
+}
+
+# Allocates tests based on the node (VM) index.
+#
+# $1 - total number of nodes
+# $2 - node index
+allocate_tests() {
+	# Keep those tests (rows) where the VM index equals the modulo:
+	local tests=$(find_tests | sort | awk "NR % $1 == $2")
+	echo "${tests}"
+}
+
+# Runs unit tests.
+#
+# $1 - tests
+# $2 - log file
+run_tests() {
+	echo 'Running tests...' >&2
+	make TESTS="$1" test-xunit >> "$2" 2>&1
+	if [[ "$?" -ne 0 ]]; then
+		echo 'Tests failed.' >&2
+		return 1
+	fi
+	echo 'Tests passed.' >&2
+	return 0
+}
+
 # Main execution sequence.
 main() {
+	local TASKS
+	local tests
+	local task
+	local len
+	local i
+
+
+	TASKS=(check_deps lint)
+	len="${#TASKS[@]}"
+
+	# Create output log files...
 	create_log_file "${log_file}"
 	if [[ "$?" -ne 0 ]]; then
 		on_error 1
 	fi
+	create_log_file "${tests_log_file}"
+	if [[ "$?" -ne 0 ]]; then
+		on_error 1
+	fi
+
+	# Start the heartbeat:
 	start_heartbeat "${heartbeat_interval}"
 
 	# Initialize the Node.js environment:
@@ -210,20 +293,33 @@ main() {
 		on_error 1
 	fi
 
-	# Assign nodes (VMs) initial tasks:
-	if [[ "${index}" = "0" ]]; then
-		check_deps "${log_file}"
-		if [[ "$?" -ne 0 ]]; then
-			on_error 1
+	# Assign nodes (VMs) tasks...
+	i="${index}"
+	while [[ "${i}" -lt "${len}" ]]; do
+		task="${TASKS}[${i}]"
+		if [[ "${task}" = "check_deps" ]]; then
+			check_deps "${log_file}"
+			if [[ "$?" -ne 0 ]]; then
+				on_error 1
+			fi
+		elif [[ "${task}" = "lint" ]]; then
+			lint "${log_file}"
+			if [[ "$?" -ne 0 ]]; then
+				on_error 1
+			fi
 		fi
-	elif [[ "${index}" = "1" ]]; then
-		lint "${log_file}"
-		if [[ "$?" -ne 0 ]]; then
-			on_error 1
-		fi
+		i=$(expr "${i}" + "${len}")
+	done
+
+	# Assign nodes (VMs) tests to run...
+	tests=$(allocate_tests "${total_nodes}" "${index}")
+	run_tests "${tests}" "${tests_log_file}"
+	if [[ "$?" -ne 0 ]]; then
+		on_error 1
 	fi
-	cleanup
+
 	print_success
+	cleanup
 	exit 0
 }
 
