build: check whether metadta fields need updating in lint workflow

diff --git a/.github/workflows/lint_changed_files.yml b/.github/workflows/lint_changed_files.yml
--- a/.github/workflows/lint_changed_files.yml
+++ b/.github/workflows/lint_changed_files.yml
@@ -148,10 +148,33 @@ jobs:
           # Define the path to a utility for linting package.json files:
           lint_package_json="${root}/lib/node_modules/@stdlib/_tools/lint/pkg-json/bin/cli"
 
+          # Define paths to utilities for updating package.json metadata fields:
+          update_package_json_directories="${root}/lib/node_modules/@stdlib/_tools/package-json/scripts/update_directories"
+          update_package_json_gypfile="${root}/lib/node_modules/@stdlib/_tools/package-json/scripts/update_gypfile"
+
           files=$(echo "${{ steps.changed-files.outputs.files }}" | tr ' ' '\n' | grep 'package\.json$' | grep -v 'datapackage\.json$' | tr '\n' ' ' | sed 's/ $//')
           if [ -n "${files}" ]; then
             echo "Linting package.json files that have changed..."
             printf "${files}" | "${lint_package_json}" --split=" "
+
+            # Check if metadata fields need to be updated:
+            dirs=$(dirname ${files})
+            needs_changes=0
+            for dir in ${dirs}; do
+              echo "Checking package.json in ${dir}..."
+              "${update_package_json_directories}" "${dir}"
+              "${update_package_json_gypfile}" "${dir}"
+              if [[ `git status --porcelain` ]]; then
+                echo "::error::Package.json in ${dir} needs updates to directories and/or gypfile fields"
+                git diff
+                needs_changes=1
+              fi
+            done
+
+            # Exit with failure if any needed changes were detected:
+            if [ $needs_changes -eq 1 ]; then
+              exit 1
+            fi
           else
             echo "No package.json files to lint."
           fi
