build: specify FPATs and add early exit step
---
type: pre_commit_static_analysis_report
description: Results of running static analysis checks when committing changes.
report:
  - task: lint_filenames
    status: passed
  - task: lint_editorconfig
    status: passed
  - task: lint_markdown
    status: na
  - task: lint_package_json
    status: na
  - task: lint_repl_help
    status: na
  - task: lint_javascript_src
    status: na
  - task: lint_javascript_cli
    status: na
  - task: lint_javascript_examples
    status: na
  - task: lint_javascript_tests
    status: na
  - task: lint_javascript_benchmarks
    status: na
  - task: lint_python
    status: na
  - task: lint_r
    status: na
  - task: lint_c_src
    status: na
  - task: lint_c_examples
    status: na
  - task: lint_c_benchmarks
    status: na
  - task: lint_c_tests_fixtures
    status: na
  - task: lint_shell
    status: na
  - task: lint_typescript_declarations
    status: na
  - task: lint_typescript_tests
    status: na
  - task: lint_license_headers
    status: passed
---

---
type: pre_push_report
description: Results of running various checks prior to pushing changes.
report:
  - task: run_javascript_examples
    status: na
  - task: run_c_examples
    status: na
  - task: run_cpp_examples
    status: na
  - task: run_javascript_readme_examples
    status: na
  - task: run_c_benchmarks
    status: na
  - task: run_cpp_benchmarks
    status: na
  - task: run_fortran_benchmarks
    status: na
  - task: run_javascript_benchmarks
    status: na
  - task: run_julia_benchmarks
    status: na
  - task: run_python_benchmarks
    status: na
  - task: run_r_benchmarks
    status: na
  - task: run_javascript_tests
    status: na
---

diff --git a/.github/workflows/run_tests_coverage.yml b/.github/workflows/run_tests_coverage.yml
--- a/.github/workflows/run_tests_coverage.yml
+++ b/.github/workflows/run_tests_coverage.yml
@@ -151,7 +151,7 @@ jobs:
         id: changed-directories
         continue-on-error: true
         env:
-          STDLIB_BOT_GITHUB_TOKEN: ${{ secrets.STDLIB_BOT_GITHUB_TOKEN }}
+          STDLIB_BOT_GITHUB_TOKEN: ${{ secrets.STDLIB_BOT_FGPAT_REPO_READ }}
         run: |
           if [ -n "${{ github.event.pull_request.number }}" ]; then
             # Get the list of changed files in pull request:
@@ -184,6 +184,18 @@ jobs:
         run: |
           echo "directories=${{ github.event.inputs.directories }}" >> $GITHUB_OUTPUT
         timeout-minutes: 5
+
+      # Exit early if non-package directories are changed:
+      - name: 'Exit early if non-package directories are changed'
+        if: github.event_name != 'workflow_dispatch'
+        run: |
+          directories="${{ steps.changed-directories.outputs.directories }}"
+          for directory in $directories; do
+            if [[ "$directory" != "lib/node_modules/@stdlib"* ]]; then
+              echo "Error: changed directory '$directory' is not in 'lib/node_modules/@stdlib'."
+              exit 1
+            fi
+          done
 
       # Run JavaScript tests:
       - name: 'Run JavaScript tests'
@@ -236,7 +248,7 @@ jobs:
         # Pin action to full length commit SHA
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         with:
-          github-token: ${{ secrets.CHATBOT_GITHUB_TOKEN }}
+          github-token: ${{ secrets.STDLIB_BOT_FGPAT_REPO_WRITE }}
           script: |
             const { data: comments } = await github.rest.issues.listComments({
               'issue_number': context.issue.number,
@@ -267,7 +279,7 @@ jobs:
         # Pin action to full length commit SHA
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         with:
-          github-token: ${{ secrets.CHATBOT_GITHUB_TOKEN }}
+          github-token: ${{ secrets.STDLIB_BOT_FGPAT_REPO_WRITE }}
           script: |
             github.rest.repos.createCommitComment({
               'commit_sha': context.sha,
@@ -294,7 +306,7 @@ jobs:
           fetch-depth: 1
 
           # Token for accessing the repository:
-          token: ${{ secrets.REPO_GITHUB_TOKEN }}
+          token: ${{ secrets.STDLIB_BOT_FGPAT_REPO_READ }}
 
       # Checkout coverage repository branch:
       - name: 'Checkout coverage repository branch'
@@ -346,7 +358,7 @@ jobs:
       # Commit and push changes:
       - name: 'Commit and push changes'
         env:
-          REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
+          REPO_GITHUB_TOKEN: ${{ secrets.STDLIB_BOT_FGPAT_REPO_WRITE }}
           USER_NAME: stdlib-bot
         run: |
           cd ./www-test-code-coverage
